# Generated by Django 3.1.7 on 2021-04-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_paypaltransactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='countrycode',
            field=models.CharField(default='US', max_length=10),
            preserve_default=False,
        ),
    ]
